[package]
name = "stream-vbyte64"
version = "0.1.0"
authors = ["Steven Fackler <sfackler@palantir.com>"]

[dependencies]
stdsimd = { git = "https://github.com/sfackler/stdsimd", branch = "const-constructor" }

[dev-dependencies]
rand = "0.3"
